version: "3.7"
services:
  app:
    stdin_open: true
    container_name: app
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Dashboard
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pgadmin-data:
