version: "3.7"
services:
  app:
    stdin_open: true
    container_name: app
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - db
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    container_name: db
    image: postgres:latest
    hostname: $HOSTNAME
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGPORT: 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "4000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PW
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pgadmin-data:
