/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {},
  daisyui: {
    themes: [
      {
        light: {
          primary: "#40936D",
          "primary-focus": "#327355",
          "primary-content": "#C4DED2",
          secondary: "#A3CEE9",
          "secondary-focus": "#B1C6D4",
          "secondary-content": "#DAEAF2",
          accent: "#868079",
          "accent-focus": "#A6998D",
          "accent-content": "#D9D5D0",
          neutral: "#6B7280",
          "neutral-focus": "#4C515B",
          "neutral-content": "#9CA1AA",
          info: "#8FC4E5",
          "info-content": "#DCEDF7",
          success: "#14B8A6",
          "success-content": "#B6E9E3",
          warning: "#FFAC0C",
          "warning-content": "#FFE5B4",
          error: "#E6624B",
          "error-content": "#F7CEC7",
          "base-100": "#D1D3D8",
          "base-200": "#F5F5F5",
          "base-300": "#16171A",
          "base-content": "#EEEFF0",
        },
      },
      {
        dark: {
          primary: "#40936D",
          "primary-focus": "#5F8E6C",
          "primary-content": "#394741",
          secondary: "#44728D",
          "secondary-focus": "#5E7387",
          "secondary-content": "#36444D",
          accent: "#616566",
          "accent-focus": "#595655",
          "accent-content": "#404040",
          neutral: "#6B7280",
          "neutral-focus": "#A0A5AE",
          "neutral-content": "#3B3F46",
          info: "#84B5D4",
          "info-content": "#668BA3",
          success: "#43C6B8",
          "success-content": "#0E8376",
          warning: "#FFBD3D",
          "warning-content": "#B57A09",
          error: "#EB816F",
          "error-content": "#A34635",
          "base-100": "#4C515B",
          "base-200": "#16171A",
          "base-300": "#F5F5F5",
          "base-content": "#2D3036",
        },
      },
    ],
  },
  plugins: [require("daisyui")],
};
