import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { BellIcon } from "@heroicons/react/24/solid";
import { StoreProvider } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <nav>
          <BellIcon className="h-12 w-12 text-primary" />
        </nav>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
