import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider, Navbar, Sidebar, ThemeProvider } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className} bg-base-content`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          defaultTheme="light"
          enableSystem={false}
          storageKey="chingu-theme"
          disableTransitionOnChange
        >
          <div className="flex flex-col h-screen">
            <Navbar />
            <StoreProvider>
              <div className="flex flex-1 overflow-hidden">
                <Sidebar />
                <main className="flex flex-col flex-1 overflow-y-auto items-center gap-y-9 p-10 w-full">
                  {children}
                </main>
              </div>
            </StoreProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
