name: Lint & Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # current LTS (we have 16 in Docker)

      - name: Install dependencies
        run: yarn install

      - name: Run Eslint
        run: yarn lint --strict

      - name: Run Jest tests
        run: yarn test

      - name: Run Cypress tests
        run: yarn cypress
