name: Lint & Test Workflow

on:
  pull_request:
    branches: [main, dev, v0.2.0]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Run Eslint
        run: yarn lint --strict

      - name: Run Jest tests
        run: yarn test

      - name: Run Cypress tests
        run: |
          if [[ ${{ github.event.pull_request.base.ref }} == 'main' ]]; then
            yarn cypress
          else
            echo "Skipping Cypress tests for non-main branch."
          fi
